apiVersion: v1
kind: Service
metadata:
  name: autotrips-service
  namespace: nodered
spec:
  type: NodePort
  selector:
    app: autotrips
  ports:
    - name: autotrips
      port: 3000
      targetPort: 1880
      nodePort: 31207
