apiVersion: apps/v1
kind: Deployment
metadata:
  name: autotrips-deployment
  namespace: nodered

spec:
  replicas: 1
  selector:
    matchLabels:
      app: autotrips
  template:
    metadata: # Dictionary
      name: autotrips-pod
      labels: # Dictionary
        app: autotrips
    spec:
      containers: # List
        - name: autotrips
          image: raghu0232/bgr-deployment:autotrips
          ports:
            - containerPort: 1880
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
            readinessProbe:
              tcpSocket:
                port: 1880
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              tcpSocket:
                port: 1880
              initialDelaySeconds: 15
              periodSeconds: 20
