apiVersion: v1
kind: Service
metadata:
  name: ct-data-2-nodeport-service
  namespace: nodered
spec:
  type: NodePort
  selector:
    app: ct-data-2
  ports:
    - name: ct-data-2
      port: 6002
      targetPort: 1880
      nodePort: 31203
