apiVersion: v1
kind: Service
metadata:
  name: ct-map-return-service
  namespace: nodered
spec:
  type: NodePort
  selector:
    app: ct-map-return
  ports:
    - name: ct-map-return
      port: 3001
      targetPort: 1880
      nodePort: 31206
