apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-map-loaded-deployment
  namespace: nodered

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct-map-loaded
  template:
    metadata: # Dictionary
      name: ct-map-loaded-pod
      labels: # Dictionary
        app: ct-map-loaded
    spec:
      containers: # List
        - name: ct-map-loaded
          image: raghu0232/bgr-deployment:ct_map_loaded
          ports:
            - containerPort: 1880
