apiVersion: v1
kind: Service
metadata:
  name: ct-ui-loaded-nodeport-service
  namespace: nodered
spec:
  type: NodePort
  selector:
    app: ct-ui-loaded
  ports:
    - name: ct-ui-loaded
      port: 3003
      targetPort: 1880
      nodePort: 31202
