apiVersion: apps/v1
kind: Deployment
metadata:
  name: labs-deployment
  namespace: nodered

spec:
  replicas: 1
  selector:
    matchLabels:
      app: labs
  template:
    metadata: # Dictionary
      name: labs-pod
      labels: # Dictionary
        app: labs
    spec:
      containers: # List
        - name: labs-container
          image: raghu0232/suvega:labs
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
          ports:
            - containerPort: 1880
          readinessProbe:
            tcpSocket:
              port: 1880
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 1880
            initialDelaySeconds: 15
            periodSeconds: 20
