apiVersion: v1
kind: Service
metadata:
  name: lab-nodeport-service
  namespace: nodered
spec:
  type: NodePort
  selector:
    app: labs
  ports:
    - name: labs
      port: 9002
      targetPort: 1880
      nodePort: 31201
