apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: nodered
spec:
  type: NodePort
  selector:
    app: mqtt
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31207
    - name: nodered
      port: 1880
      targetPort: 1880
