apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  namespace: nodered
spec:
  type: NodePort
  selector:
    app: mqtt
  ports:
    - name: mqtt
      port: 5000
      targetPort: 1883
      nodePort: 31207
