apiVersion: v1
kind: Service
metadata:
  name: xlabs-nodeport-service
  namespace: nodered
spec:
  type: NodePort
  selector:
    app: xlabs
  ports:
    - name: http
      port: 9001
      targetPort: 1880
      nodePort: 31200
